### ISSUE TITLE
Reveal the OWLViz tab in Protege

### ISSUE THREAD

**Issue by rogerdielrton** [protegeproject/owlviz#16]
Excuseme for the question, but, how can I show (to make visible) the OWLViz tab where the graph diagram is painted?
I'm getting crazy!

**Comment by csnyulas** [comment]
This is a question for our Protege User support mailing list [1] rather then an issue per se.
You can activate the OWLViz tab in the following menu: Go to Window -> Tabs -> OwlViz

[1] http://protege.stanford.edu/support.php

**Comment by rogerdielrton** [comment]
Sorry for my mistake, but, It cannot be overemphasized to include the paragraph:

> You can activate the OWLViz tab in the following menu: Go to Window -> Tabs -> OwlViz

into the README.md.

**Comment by csnyulas** [comment]
Done. Thanks for the suggestion.
