### ISSUE TITLE
Export image does not work

### ISSUE THREAD

**Issue by wzw728** [protegeproject/owlviz#2]
Protege 5.0.0
OWLViz 4.1.4
graphviz 2.30.1

When I export image and set Scale export 200(or just >100), I just get the 1/4 image and It is around black backgrond. I also had tried graphviz 2.38 and 2.39.
What should I do to fix it?

**Comment by tudorache** [comment]
Reproduced the bug with:

Protege 5.0.0
OWLViz 4.1.4
graphviz 2.36.0

The only workaround I can think of is not to use the scaling, although I can see it is inconvenient.

**Comment by FilipeSantana** [comment]
With:
Protégé 5.0.0
OWLViz 4.1.4
Graphviz 2.38

It still does not work. The inability to properly scale images using OWLViz is not a new issue. 
I really do not know if it is a GraphViz issue or a OWLViz issue. The issue gets worse if, during the first export task, you modify the characteristics of the resultant (png or jpg) file.
![teste2](https://cloud.githubusercontent.com/assets/11309864/7931188/a381b004-090e-11e5-9c0d-f463f2b38e1b.png) (png, antialiased, scale 300)

The final quality of image is too low (.png) with default configuration to perform modifications.

It also may be related to memory. When loading huge ontologies, or too many imported files, OWLViz takes time to load.

**Comment by benedikt90** [comment]
same here.
Protégé 5.0.0 (b21)
OWLViz 4.1.4
Graphviz 2.38
Windows 8.1 x64
running protege in usermode
